[project]
name = "semantic-search-with-amazon-opensearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sentence-transformers>=5.0.0",
]
